---
# SSH connection settings
ansible_user: <WINDOWS_USER>   # Replace with your Windows username
ansible_password: "{{ vars['vault_windows_password'] }}"
ansible_connection: ssh
ansible_shell_type: powershell
ansible_port: 22

# WireGuard installer
wireguard_installer_url: "https://download.wireguard.com/windows-client/wireguard-installer.exe"
wireguard_installer_dest: 'C:\Windows\Temp\wireguard-installer.exe'

# Installation paths on Windows
wireguard_install_dir: 'C:\Program Files\WireGuard'
wireguard_exe: 'C:\Program Files\WireGuard\wireguard.exe'
wireguard_config_dir: 'C:\Program Files\WireGuard\Data\Configurations'

